### PR TITLE
Fix make install on macOS

### LINKED ISSUE #7: macOS --parents
Related to issue #2, macOS does not support `--parents` flag also for the `cp` command. Actually, `cp` does not support the `--` option syntax at all (not sure why O.o). Fortunately, the installation works fine after removing all unsupported flags (since all directories are created by `mkdir`anyway, and `--verbose` is just verbose).

### PR DESCRIPTION
**Pull request by daemontus**
- --verbose -> -v
 - remove --parents

Closes #7

### CODE REVIEW

**Comment by Witiko** [comment]
The `--parents` flag is significant, though. The `mkdir` commands will only create the base directories and without the `--parents` flag, the internal structure of the directories will not be preserved after the copy. The effect of the `--parents` flag is as follows:

 - `cp a/b/c d/` creates `d/c`.
 - `cp --parents a/b/c d/` creates `d/a/b/c`.

This is my output from the modified Makefile:

```
$ make implode && make
[...]
$ make install to=~/tmp
mkdir -p "/home/witiko/tmp/tex/latex/fithesis"
cp -v fithesis.cls fithesis2.cls fithesis3.cls style/*.sty style/*/*.sty style/*/*.clo logo/*/*.eps logo/*/*.pdf locale/*.def locale/*/*.def locale/*/*/*.def "/home/witiko/tmp/tex/latex/fithesis"
'fithesis.cls' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis.cls'
'fithesis2.cls' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis2.cls'
'fithesis3.cls' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis3.cls'
'style/fithesis-base.sty' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-base.sty'
cp: will not overwrite just-created '/home/witiko/tmp/tex/latex/fithesis/fithesis-base.sty' with 'style/mu/fithesis-base.sty'
'style/mu/fithesis-econ.sty' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-econ.sty'
'style/mu/fithesis-fi.sty' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-fi.sty'
'style/mu/fithesis-fsps.sty' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-fsps.sty'
'style/mu/fithesis-fss.sty' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-fss.sty'
'style/mu/fithesis-law.sty' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-law.sty'
'style/mu/fithesis-med.sty' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-med.sty'
'style/mu/fithesis-ped.sty' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-ped.sty'
'style/mu/fithesis-phil.sty' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-phil.sty'
'style/mu/fithesis-sci.sty' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-sci.sty'
'style/mu/fithesis-10.clo' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-10.clo'
'style/mu/fithesis-11.clo' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-11.clo'
'style/mu/fithesis-12.clo' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-12.clo'
'logo/mu/fithesis-base-color.eps' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-base-color.eps'
'logo/mu/fithesis-base.eps' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-base.eps'
'logo/mu/fithesis-econ-color.eps' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-econ-color.eps'
'logo/mu/fithesis-econ.eps' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-econ.eps'
'logo/mu/fithesis-fi-color.eps' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-fi-color.eps'
'logo/mu/fithesis-fi-color_.eps' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-fi-color_.eps'
'logo/mu/fithesis-fi-color__.eps' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-fi-color__.eps'
'logo/mu/fithesis-fi.eps' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-fi.eps'
'logo/mu/fithesis-fsps-color.eps' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-fsps-color.eps'
'logo/mu/fithesis-fsps.eps' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-fsps.eps'
'logo/mu/fithesis-fss-color.eps' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-fss-color.eps'
'logo/mu/fithesis-fss.eps' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-fss.eps'
'logo/mu/fithesis-law-color.eps' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-law-color.eps'
'logo/mu/fithesis-law.eps' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-law.eps'
'logo/mu/fithesis-med-color.eps' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-med-color.eps'
'logo/mu/fithesis-med.eps' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-med.eps'
'logo/mu/fithesis-ped-color.eps' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-ped-color.eps'
'logo/mu/fithesis-ped.eps' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-ped.eps'
'logo/mu/fithesis-phil-color.eps' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-phil-color.eps'
'logo/mu/fithesis-phil.eps' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-phil.eps'
'logo/mu/fithesis-sci-color.eps' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-sci-color.eps'
'logo/mu/fithesis-sci.eps' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-sci.eps'
'logo/mu/fithesis-base-color.pdf' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-base-color.pdf'
'logo/mu/fithesis-base.pdf' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-base.pdf'
'logo/mu/fithesis-econ-color.pdf' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-econ-color.pdf'
'logo/mu/fithesis-econ.pdf' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-econ.pdf'
'logo/mu/fithesis-fi-color.pdf' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-fi-color.pdf'
'logo/mu/fithesis-fi.pdf' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-fi.pdf'
'logo/mu/fithesis-fsps-color.pdf' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-fsps-color.pdf'
'logo/mu/fithesis-fsps.pdf' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-fsps.pdf'
'logo/mu/fithesis-fss-color.pdf' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-fss-color.pdf'
'logo/mu/fithesis-fss.pdf' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-fss.pdf'
'logo/mu/fithesis-law-color.pdf' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-law-color.pdf'
'logo/mu/fithesis-law.pdf' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-law.pdf'
'logo/mu/fithesis-med-color.pdf' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-med-color.pdf'
'logo/mu/fithesis-med.pdf' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-med.pdf'
'logo/mu/fithesis-ped-color.pdf' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-ped-color.pdf'
'logo/mu/fithesis-ped.pdf' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-ped.pdf'
'logo/mu/fithesis-phil-color.pdf' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-phil-color.pdf'
'logo/mu/fithesis-phil.pdf' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-phil.pdf'
'logo/mu/fithesis-sci-color.pdf' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-sci-color.pdf'
'logo/mu/fithesis-sci.pdf' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-sci.pdf'
'locale/fithesis-czech.def' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-czech.def'
'locale/fithesis-english.def' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-english.def'
'locale/fithesis-slovak.def' -> '/home/witiko/tmp/tex/latex/fithesis/fithesis-slovak.def'
cp: will not overwrite just-created '/home/witiko/tmp/tex/latex/fithesis/fithesis-czech.def' with 'locale/mu/fithesis-czech.def'
cp: will not overwrite just-created '/home/witiko/tmp/tex/latex/fithesis/fithesis-english.def' with 'locale/mu/fithesis-english.def'
cp: will not overwrite just-created '/home/witiko/tmp/tex/latex/fithesis/fithesis-slovak.def' with 'locale/mu/fithesis-slovak.def'
cp: will not overwrite just-created '/home/witiko/tmp/tex/latex/fithesis/fithesis-czech.def' with 'locale/mu/econ/fithesis-czech.def'
cp: will not overwrite just-created '/home/witiko/tmp/tex/latex/fithesis/fithesis-english.def' with 'locale/mu/econ/fithesis-english.def'
cp: will not overwrite just-created '/home/witiko/tmp/tex/latex/fithesis/fithesis-slovak.def' with 'locale/mu/econ/fithesis-slovak.def'
cp: will not overwrite just-created '/home/witiko/tmp/tex/latex/fithesis/fithesis-czech.def' with 'locale/mu/fi/fithesis-czech.def'
cp: will not overwrite just-created '/home/witiko/tmp/tex/latex/fithesis/fithesis-english.def' with 'locale/mu/fi/fithesis-english.def'
cp: will not overwrite just-created '/home/witiko/tmp/tex/latex/fithesis/fithesis-slovak.def' with 'locale/mu/fi/fithesis-slovak.def'
cp: will not overwrite just-created '/home/witiko/tmp/tex/latex/fithesis/fithesis-czech.def' with 'locale/mu/fsps/fithesis-czech.def'
cp: will not overwrite just-created '/home/witiko/tmp/tex/latex/fithesis/fithesis-english.def' with 'locale/mu/fsps/fithesis-english.def'
cp: will not overwrite just-created '/home/witiko/tmp/tex/latex/fithesis/fithesis-slovak.def' with 'locale/mu/fsps/fithesis-slovak.def'
cp: will not overwrite just-created '/home/witiko/tmp/tex/latex/fithesis/fithesis-czech.def' with 'locale/mu/fss/fithesis-czech.def'
cp: will not overwrite just-created '/home/witiko/tmp/tex/latex/fithesis/fithesis-english.def' with 'locale/mu/fss/fithesis-english.def'
cp: will not overwrite just-created '/home/witiko/tmp/tex/latex/fithesis/fithesis-slovak.def' with 'locale/mu/fss/fithesis-slovak.def'
cp: will not overwrite just-created '/home/witiko/tmp/tex/latex/fithesis/fithesis-czech.def' with 'locale/mu/law/fithesis-czech.def'
cp: will not overwrite just-created '/home/witiko/tmp/tex/latex/fithesis/fithesis-english.def' with 'locale/mu/law/fithesis-english.def'
cp: will not overwrite just-created '/home/witiko/tmp/tex/latex/fithesis/fithesis-slovak.def' with 'locale/mu/law/fithesis-slovak.def'
cp: will not overwrite just-created '/home/witiko/tmp/tex/latex/fithesis/fithesis-czech.def' with 'locale/mu/med/fithesis-czech.def'
cp: will not overwrite just-created '/home/witiko/tmp/tex/latex/fithesis/fithesis-english.def' with 'locale/mu/med/fithesis-english.def'
cp: will not overwrite just-created '/home/witiko/tmp/tex/latex/fithesis/fithesis-slovak.def' with 'locale/mu/med/fithesis-slovak.def'
cp: will not overwrite just-created '/home/witiko/tmp/tex/latex/fithesis/fithesis-czech.def' with 'locale/mu/ped/fithesis-czech.def'
cp: will not overwrite just-created '/home/witiko/tmp/tex/latex/fithesis/fithesis-english.def' with 'locale/mu/ped/fithesis-english.def'
cp: will not overwrite just-created '/home/witiko/tmp/tex/latex/fithesis/fithesis-slovak.def' with 'locale/mu/ped/fithesis-slovak.def'
cp: will not overwrite just-created '/home/witiko/tmp/tex/latex/fithesis/fithesis-czech.def' with 'locale/mu/phil/fithesis-czech.def'
cp: will not overwrite just-created '/home/witiko/tmp/tex/latex/fithesis/fithesis-english.def' with 'locale/mu/phil/fithesis-english.def'
cp: will not overwrite just-created '/home/witiko/tmp/tex/latex/fithesis/fithesis-slovak.def' with 'locale/mu/phil/fithesis-slovak.def'
cp: will not overwrite just-created '/home/witiko/tmp/tex/latex/fithesis/fithesis-czech.def' with 'locale/mu/sci/fithesis-czech.def'
cp: will not overwrite just-created '/home/witiko/tmp/tex/latex/fithesis/fithesis-english.def' with 'locale/mu/sci/fithesis-english.def'
cp: will not overwrite just-created '/home/witiko/tmp/tex/latex/fithesis/fithesis-slovak.def' with 'locale/mu/sci/fithesis-slovak.def'
Makefile:161: recipe for target 'install-base' failed
make: *** [install-base] Error 1
```

Perhaps it would be best to replace `cp` with `tar` to achieve better macOS support. Replacing

```
cp --parents --verbose $^ "$$DIR/fithesis"
```

with

```
tar c $^ | tar xvC "$$DIR/fithesis"
```

preserves the semantics and might actually be supported by the tools available on a macOS installation.

**Comment by daemontus** [comment]
Ok, I'll look at this over the weekend and update the pull request. Meanwhile thanks for the info :)

**Comment by Witiko** [comment]
Do you have any updates on this issue?

**Comment by daemontus** [comment]
Sorry, forgot about this. But I found other (maybe even better) solution - [rsync](https://en.wikipedia.org/wiki/Rsync) - it is present on both macOS and common linux distros and should be able to do the same thing as cp --parents. So can I replace it with rsync, or are we sticking with tar?

**Comment by Witiko** [comment]
It is available, but usually not preinstalled, whereas `tar` is basically guaranteed to be always there. Therefore, I would much prefer the `tar` solution.

**Pull request closed without merging**
